# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/IfcOpenHouse',
                'doc_host': 'https://cvillagrasa.github.io',
                'git_url': 'https://github.com/cvillagrasa/IfcOpenHouse',
                'lib_path': 'IfcOpenHouse'},
  'syms': {'IfcOpenHouse.core': {}, 'IfcOpenHouse.ios_utils': {}, 'IfcOpenHouse.opening_data': {}}}
