project:
  type: website

format:
  html:
    theme: quartz
    css: styles.css
    toc: true
    page-layout: article
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true
    code-block-bg: "#aec7d4"
    code-block-border-left: false
    include-after-body:
      text: |
        <script src="https://cdn.jsdelivr.net/gh/cvillagrasa/IfcOpenHouse@latest/viz/bundle_quarto.js" />

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
  sidebar:
    style: floating

metadata-files: [nbdev.yml, sidebar.yml]